"use client";
import { useEffect, useState } from "react";
import { Landmark, Plus, Trash2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { AppHeader } from "@/components/app/navigation";
import { Button, Card, Input, Modal, Select } from "@/components/ui";
import { accountTypes, formatRupiah, type Account } from "@/lib/financial";
export default function AccountsPage(){const supabase=createClient();const [items,setItems]=useState<Account[]>([]);const [familyId,setFamilyId]=useState("");const [open,setOpen]=useState(false);const [name,setName]=useState("");const [type,setType]=useState("cash");const [balance,setBalance]=useState("0");const [error,setError]=useState("");
 async function load(){const {data:m}=await supabase.from("family_members").select("family_id").limit(1).maybeSingle();if(!m)return;setFamilyId(m.family_id);const {data}=await supabase.from("accounts").select("id,name,account_type,color,opening_balance,is_archived").eq("family_id",m.family_id).eq("is_archived",false).order("created_at");setItems((data||[]) as Account[])}useEffect(()=>{load()},[]);
 async function save(e:React.FormEvent){e.preventDefault();setError("");const {error:e2}=await supabase.from("accounts").insert({family_id:familyId,name:name.trim(),account_type:type,opening_balance:Number(balance.replace(/\D/g,""))||0,created_by:(await supabase.auth.getUser()).data.user?.id});if(e2)setError(e2.message);else{setOpen(false);setName("");setBalance("0");load()}}
 async function remove(id:string){if(!confirm("Arsipkan rekening ini?"))return;await supabase.from("accounts").update({is_archived:true}).eq("id",id).eq("family_id",familyId);load()}
 return <><AppHeader title="Rekening" subtitle="Sumber uang keluarga" action={<Button onClick={()=>setOpen(true)}><Plus size={16}/> Tambah</Button>}/>{items.length?<div className="account-grid">{items.map((a,i)=><Card className="account-card" key={a.id} style={{"--account-color":a.color} as React.CSSProperties}><Landmark size={20} color={a.color}/><small>{accountTypes[a.account_type]||"Lainnya"}</small><strong>{a.name}</strong><div style={{fontSize:22,fontWeight:800,marginTop:8}}>{formatRupiah(Number(a.opening_balance))}</div><footer><span>Saldo awal</span><button onClick={()=>remove(a.id)} aria-label="Arsipkan"><Trash2 size={14}/></button></footer></Card>)}</div>:<Card className="empty"><Landmark size={30}/><strong>Belum ada rekening</strong>Tambahkan kas, bank, atau e-wallet keluarga.</Card>}<Modal open={open} title="Tambah rekening" onClose={()=>setOpen(false)}><form onSubmit={save}><div className="form-grid"><div className="field form-full"><label>Nama rekening</label><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Kas Utama" required/></div><div className="field"><label>Jenis</label><Select value={type} onChange={e=>setType(e.target.value)}>{Object.entries(accountTypes).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select></div><div className="field"><label>Saldo awal</label><Input inputMode="numeric" value={balance} onChange={e=>setBalance(e.target.value.replace(/\D/g,""))}/></div></div>{error&&<div className="notice error" style={{marginTop:14}}>{error}</div>}<div className="form-actions"><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Batal</Button><Button>Simpan</Button></div></form></Modal></>}
